sfmc:
  client_secret: "Mc5cCcp2f34Iv5XZnLvJRwso"
sfdc:
  keystore_pw: "Tb20YtrPym9jL2Gd"
runtime:
  passcode: "3ncryptP@ssw0rd"
onetrust:
  api_token: "ZjIxOTNhZTkyYjQwNDRmYmJjYzFkZjNjMjAxZDY2ZDA6Qzl3WklxdEg2NXp5QkFjOFNJYVN4WG5ETjYyNUxRaUg="
messageQueue:
  client_secret: "C162335CDce14A9F90010cc2143Ef6C1"
cloudhub:
  #see Keeper: WSD-READ-APPLICATION
  password: "C8d1Ab5059B44Ff4831F4Be5d4EAe3d0"
