sfmc:
  client_secret: "![k3czvLeeovsLpKFrkvsG3AKq6p5hD7DiMj+u8ev3yLY=]"
sfdc:
  keystore_pw: "![CwaiIkPZt7ffAd3sfcg4IfEVmkhI+Hs3]"
runtime:
  passcode: "![5zeEaEuWHZ/Wg9neNjfBXA==]"
cloudhub:
  password: "![GDriVQgyTQuKiMA9TgwWGz3B5lSDV++fPMgTnYsyATOz+BVbZoaz6w==]"
