sfmc:
  client_secret: "![k3czvLeeovsLpKFrkvsG3AKq6p5hD7DiMj+u8ev3yLY=]"
sfdc:
  keystore_pw: "![CwaiIkPZt7ffAd3sfcg4IfEVmkhI+Hs3]"
runtime:
  passcode: "![5zeEaEuWHZ/Wg9neNjfBXA==]"
onetrust:
  api_token: "![oHYTC4lnM72+c/DJQSOkK/thBVMTp803k8fZiPpi9/6+bbvD+99YM8Y/8icO0B9tpgjTgBhBUpSG72QsQFnL+4othWVFh8YQ9E5Kfg1RthfJ40LbZj1gJXRdErVuW1j4]"
messageQueue:
  client_secret: "![3JPeoJT7iUd5oIj1q331gquTfYJO+Iqy2dbWPhqp2a+2GcEwyYxunw==]"
cloudhub:
#see Keeper: WSD-READ-APPLICATION
  password: "![GDriVQgyTQuKiMA9TgwWGz3B5lSDV++fPMgTnYsyATOz+BVbZoaz6w==]"
