sfmc:
  client_secret: "Mc5cCcp2f34Iv5XZnLvJRwso"
sql:
  password: "HSTKt3st4dm1n"
scuba:
  password: "v6y!YkPm43du]"
runtime:
  passcode: "3ncryptP@ssw0rd"
cloudhub:
  password: "C8d1Ab5059B44Ff4831F4Be5d4EAe3d0"
