sfmc:
  client_secret: "![0Ya4IU4+yBqZAlEhLMXglBwtm48BEC/gnaIdfDoTk5Q=]"
sql:
  password: "![Gi61vFlciFt9itNn8Nl13A==]"
scuba:
  password: "![YKKqTMhnGQDmIseFN5IXUg==]"
runtime:
  passcode: "![5zeEaEuWHZ/Wg9neNjfBXA==]"
