sfmc:
  client_id: "zzrzoenezrlwv61agervfb5u"
  client_secret: "mEOAxhsa9fgX0G1aaG9ln7JM"
  token_url: "https://mcv7128ncglg133p2kjr3ml9t338.auth.marketingcloudapis.com/v2/token"
  subdomain: "mctbbslbdjnl732r4zv089b47m90"
  account_id: "7207804"
  data_extension:
    external_key: "637099D6-BB83-4386-A92D-93747B35B377"
sfdc:
  consumer_key: "3MVG95jctIhbyCpqWacYp6bth1.2WeFHLdd0UsdyJ4nBHY6TyNVhtrVD3SrrSTwacY6hT.Mhzxd6JBZXKsv7s"
  keystore: "csmule.jks"
  token_endpoint: "https://ucsf-clinicalcrm.my.salesforce.com/services/oauth2/token"
  principal: "otintegrationuser@ucsf.edu"
  #audience_url: "https://ucsf-clinicalcrm.my.salesforce.com/"
  audience_url: "https://login.salesforce.com"
runtime:
  passcode: "3ncryptP@ssw0rd"
onetrust:
  host: "na01.onetrust.com"
  privacy_host: "privacyportal-na01.onetrust.com"
  pref_url: "https://privacyportal-na01.onetrust.com/ui/#/preferences/multipage/token/"
  #click on user icon, id under username
  tenant_id: "896caafa-eb04-4d8a-887e-1808eed69804"
  is_test: "false"
  patient_collection_pt: "6ce6ed5c-7dd2-4ec1-aaf4-d7109a73c0c3" #TODO: change when Patient is in PROD
messageQueue:
  mqUrl: "https://mq-us-west-2.anypoint.mulesoft.com/api/v1/organizations/8f9ff49c-7213-45d6-ae70-a89968883c15/environments/567bad7d-43a7-4c51-b74f-fde6f3ea9217"
  client_id: "72b7cc294c10436ca554928e366c8453"
  queueName: "consent-receipt-sfdc-lead-in"
  circuitBreaker:
    errors: "HTTP:SERVICE_UNAVAILABLE, HTTP:CONNECTIVITY, HTTP:TIMEOUT, HTTP:RETRY_EXHAUSTED, HTTP:TOO_MANY_REQUESTS, HTTP:UNAUTHORIZED, HTTP:NOT_FOUND, MULE:RETRY_EXHAUSTED"
    threshold: "3"
    tripTimeout: "2"
cloudhub:
  #see Keeper: WSD-READ-APPLICATION
  clientid: "cf2ea576bb2c4c8e864d333dc0c1c95a"
  #see AccessMgmt-BusinessGrp-{env} urlpath
  environment: "567bad7d-43a7-4c51-b74f-fde6f3ea9217"
  domain: "prod-mec-salesforce-subscriber"

